pipeline {
    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout to github repo') {
            steps {
                git branch: 'main',
                credentialsId: 'Github_details',
                url: 'https://github.com/Santhosh107-star/Docker.git'
            }
        }

        stage('Build the docker image') {
            steps {
                script {
                    sh '''
                    echo 'Build docker image'
                    docker build -t santhosh2025/cicd-e2e:${IMAGE_TAG} -f python-flask-app/Dockerfile python-flask-app
                    '''
                }
            }
        }

        stage('Push the docker image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_TOKEN'
                )]) {
                    sh '''
                    echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push santhosh2025/cicd-e2e:${IMAGE_TAG}
                    docker logout
                    '''
                }
            }
        }

        stage('Update the k8 deploy file') {
          steps {
            script {
              withCredentials([usernamePassword(
                credentialsId: 'Github_details',
                passwordVariable: 'GIT_TOKEN',
                usernameVariable: 'GIT_USERNAME'
            )]) {

                sh '''
                cat python-flask-app/k8/deploy.yaml
                sed -i "s|image: santhosh2025/cicd-e2e:.*|image: santhosh2025/cicd-e2e:${IMAGE_TAG}|" python-flask-app/k8/deploy.yaml

                git config user.email "jenkins@ci.com"
                git config user.name "jenkins"

                git add python-flask-app/k8/deploy.yaml
                git commit -m "update deploy yaml file with latest tag ${IMAGE_TAG}" || echo "No changes to commit"

                git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/Santhosh107-star/Docker.git HEAD:main
                '''
                }
            }
          }
        }
    }
}